settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: sine-zip # unique identifier
    name: sine.zip
    description: 'I aint' good with no words.' # default=empty
    url: 'https://sine.zip' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: image-sine-zip
    name: image.sine.zip
    description: 'Images what?????'
    url: 'https://image.sine.zip'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: image-sine-zip
    name: cdn.sine.zip
    description: 'cdn getm somewhere what?????'
    url: 'https://cdn.sine.zip'
    method: GET
    expectStatus: 200
